on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install --omit=dev

      - name: Add bot descriptors
        run: |
          mv ${GITHUB_WORKSPACE}/masin.js ${GITHUB_WORKSPACE}/IIlIllIlII.js

      - name: Create bot zip
        run: |
          pwd
          rm -rf ${GITHUB_WORKSPACE}/IIlIllIlII.zip
          zip -r ${GITHUB_WORKSPACE}/IIlIllIlII.zip . -x '.git/*' '.github/*'
          ls -l ${GITHUB_WORKSPACE}

      - name: Upload to AI Arena
        env:
          API_TOKEN: ${{ secrets.AI_ARENA_API_TOKEN }}
        run: |
          curl -X PATCH -H "Authorization: Token ${API_TOKEN}" -F "bot_zip=@${GITHUB_WORKSPACE}/IIlIllIlII.zip" https://aiarena.net/api/bots/984/
